DEVICE          : cpu              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output'         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : Vdet_for_java                                      # name of the model you are using
  BACKBONE      :
  PARAMS:                                                   # model variant
    encoder       : 
    config        :
    tokenizer     : 
    args          :
        config_name : ''
  PRETRAINED    : 'checkpoints/backbones/xx.pth'              # backbone model's weight 

DATASET:
  NAME          : vdet_data                                         # dataset name to be trained
  ROOT          : ''                         # dataset root path
  PARAMS:
    tokenizer   : 'roberta'
    args        :
      train_file : '/Users/asteriska/Asteriska/nwu/projects/ASTERIA-Detection/external/VDET/train.csv'
      eval_file : '/Users/asteriska/Asteriska/nwu/projects/ASTERIA-Detection/external/VDET/val.csv'
      training_percent: 1.0
  PREPROCESS:
    ENABLE      : False #True
    COMPOSE     : [ 
                "Normalize",
                "PadSequence",
                "OneHotEncode"
        ]
      


TRAIN:
  INPUT_SIZE    : 128
  BATCH_SIZE    : 64               # batch size used to train
  EPOCHS        : 4             # number of epochs to train
  EVAL_INTERVAL : 1              # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : CrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.001           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 0              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  INPUT_SIZE    : 128
  MODEL_PATH    : 'checkpoints/pretrained/vuln.pth'  # trained model file path
  MSF: 
    ENABLE      : false                                                                 # multi-scale and flip evaluation  
    FLIP        : true                                                                  # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]                                     # scales used in MSF evaluation                


TEST:
  MODEL_PATH    : 'checkpoints/pretrained/vuln.pth'  # trained model file path
  FILE          : 'assests/ade'                                                         # filename or foldername 
  INPUT_SIZE    : 128                                                            # inference input size
  OVERLAY       : true                                                                  # save the result